name = "backend"
compatibility_date = "2024-07-30"
node_compat = true


[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTU2OGZkMTUtMjkxNC00YWNhLTg0ZmMtNjk4N2E2ZWI4NTVlIiwidGVuYW50X2lkIjoiNGRiZTJlMTE2NmM4Y2M5ODJlZDViY2MxYjI2OTcxYjYwNTI2NjUxNzNiM2QwZjdhNDFkYzgxNGFjNjM5NmEzNCIsImludGVybmFsX3NlY3JldCI6IjkzOWNkNDVjLWQxZTctNDU4My1hNjExLTM0MTM3MTNiOWY5MyJ9.gYcDPKaXeUiuChb4W_7xd8Bur9QLdJkc-5jpDfHi-8E"
SALT_ROUNDS = "10"
JWT_SECRET = "123456"
